using System.Text;

namespace NetworkOptimizer.Core.Helpers;

/// <summary>
/// Encoding for text files written to a gateway (boot scripts, systemd units, authorized_keys).
///
/// Gateways execute these as shell scripts and parse them as unit files, and a carriage return is
/// not whitespace to either: a script whose shebang reads "#!/bin/sh\r" makes the kernel look for an
/// interpreter literally named "/bin/sh\r" and fail. Nothing in C# protects against that - raw string
/// literals, verbatim strings and StringBuilder.AppendLine all carry the build host's line endings
/// through to the output - so content generated by a Windows build arrives with CRLF while the same
/// code built on Linux arrives with LF.
///
/// Encoding through here is what makes the bytes on the gateway independent of the machine that
/// built the app. Do not call Convert.ToBase64String directly on gateway-bound text; the
/// architecture test in NetworkOptimizer.Web.Tests fails when a new deployment path does.
/// </summary>
public static class GatewayFile
{
    /// <summary>
    /// Base64 of <paramref name="content"/> with line endings normalized to LF, ready to pipe
    /// through "base64 -d" on the gateway. Normalization is idempotent, so content that already
    /// uses LF encodes byte-for-byte identically.
    /// </summary>
    public static string ToBase64(string content) =>
        Convert.ToBase64String(Encoding.UTF8.GetBytes(ToUnixText(content)));

    /// <summary>
    /// <paramref name="content"/> with CRLF and lone CR line endings collapsed to LF.
    /// </summary>
    public static string ToUnixText(string content) =>
        content.Replace("\r\n", "\n").Replace("\r", "\n");
}
