using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetworkOptimizer.Storage.Migrations
{
    /// <summary>
    /// Migrate external speed test server config from key-value SystemSettings
    /// to a proper ExternalSpeedTestServers table with ServerId for deploy commands.
    /// </summary>
    public partial class AddExternalSpeedTestServers : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ExternalSpeedTestServers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ServerId = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    Host = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    Port = table.Column<int>(type: "INTEGER", nullable: false),
                    Scheme = table.Column<string>(type: "TEXT", maxLength: 10, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExternalSpeedTestServers", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ExternalSpeedTestServers_ServerId",
                table: "ExternalSpeedTestServers",
                column: "ServerId",
                unique: true);

            // Migrate existing key-value settings into the new table.
            // The ServerId is generated by lowercasing the name and replacing non-alphanumeric with hyphens.
            // SQLite doesn't have LOWER() with full Unicode, but server names are typically ASCII.
            migrationBuilder.Sql(@"
                INSERT INTO ExternalSpeedTestServers (ServerId, Name, Host, Port, Scheme, CreatedAt)
                SELECT
                    COALESCE(
                        NULLIF(
                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                LOWER(TRIM(COALESCE(NULLIF((SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.name'), ''), 'external'))),
                            ' ', '-'), '.', '-'), '_', '-'), '(', '-'), ')', '-'), '--', '-'),
                        ''),
                        'external'
                    ),
                    COALESCE(NULLIF((SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.name'), ''), 'External Server'),
                    (SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.host'),
                    COALESCE(CAST((SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.port') AS INTEGER), 3005),
                    COALESCE((SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.scheme'), 'https'),
                    datetime('now')
                WHERE (SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.host') IS NOT NULL
                    AND (SELECT Value FROM SystemSettings WHERE Key = 'external_speedtest.host') != '';
            ");

            // Remove old key-value settings
            migrationBuilder.Sql("DELETE FROM SystemSettings WHERE Key LIKE 'external_speedtest.%';");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Migrate data back to key-value settings
            migrationBuilder.Sql(@"
                INSERT INTO SystemSettings (Key, Value, CreatedAt, UpdatedAt)
                SELECT 'external_speedtest.host', Host, CreatedAt, CreatedAt FROM ExternalSpeedTestServers LIMIT 1;
            ");
            migrationBuilder.Sql(@"
                INSERT INTO SystemSettings (Key, Value, CreatedAt, UpdatedAt)
                SELECT 'external_speedtest.port', CAST(Port AS TEXT), CreatedAt, CreatedAt FROM ExternalSpeedTestServers LIMIT 1;
            ");
            migrationBuilder.Sql(@"
                INSERT INTO SystemSettings (Key, Value, CreatedAt, UpdatedAt)
                SELECT 'external_speedtest.scheme', Scheme, CreatedAt, CreatedAt FROM ExternalSpeedTestServers LIMIT 1;
            ");
            migrationBuilder.Sql(@"
                INSERT INTO SystemSettings (Key, Value, CreatedAt, UpdatedAt)
                SELECT 'external_speedtest.name', Name, CreatedAt, CreatedAt FROM ExternalSpeedTestServers LIMIT 1;
            ");

            migrationBuilder.DropTable(name: "ExternalSpeedTestServers");
        }
    }
}
