using NetworkOptimizer.Core.Helpers;
using NetworkOptimizer.Reports;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NetworkOptimizer.Web.Services.Firmware;

/// <summary>
/// Renders a <see cref="RolloutReport"/> as a PDF, following the Security Audit and ISP Health
/// reports' page setup, branding and section styling (<see cref="PdfReportGenerator"/>).
///
/// It computes nothing: the report handed in is the one the page renders, so the export cannot
/// drift from the screen.
/// </summary>
public class RolloutReportPdfGenerator
{
    private readonly BrandingOptions _branding;
    private readonly byte[]? _logoBytes;

    /// <param name="branding">Branding overrides; the product defaults are used when null.</param>
    public RolloutReportPdfGenerator(BrandingOptions? branding = null)
    {
        _branding = branding ?? BrandingOptions.OzarkConnect();
        QuestPDF.Settings.License = LicenseType.Community;
        _logoBytes = ReportAssets.Logo();
    }

    /// <summary>Renders the report to PDF bytes.</summary>
    /// <param name="report">The persisted soak report, exactly as the page received it.</param>
    /// <param name="siteName">Site the rollout covered, used in the title.</param>
    public byte[] GenerateReportBytes(RolloutReport report, string? siteName = null)
    {
        ArgumentNullException.ThrowIfNull(report);

        var generatedAt = DateTime.Now;
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.Letter);
                page.Margin(0.5f, Unit.Inch);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Black));

                page.Header().Element(c => ComposeHeader(c, report, siteName, generatedAt));
                page.Content().Element(c => ComposeContent(c, report));
                page.Footer().Element(c => ComposeFooter(c, generatedAt));
            });
        }).GeneratePdf();
    }

    private void ComposeHeader(IContainer container, RolloutReport report, string? siteName, DateTime generatedAt)
    {
        container.Column(column =>
        {
            if (_logoBytes is { Length: > 0 })
                column.Item().AlignLeft().MaxWidth(1.5f, Unit.Inch).Image(_logoBytes);

            var title = string.IsNullOrWhiteSpace(siteName)
                ? "Firmware Rollout Report"
                : $"{siteName} Firmware Rollout Report";

            column.Item().AlignCenter().Text(title).FontSize(22).Bold().FontColor(_branding.Colors.Primary);

            column.Item().AlignLeft().PaddingTop(6)
                .Text($"Generated: {generatedAt:MMMM dd, yyyy HH:mm}    Rollout: {WindowLabel(report)}")
                .FontSize(10).FontColor(Colors.Grey.Medium);

            column.Item().PaddingBottom(10).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposeFooter(IContainer container, DateTime generatedAt)
    {
        container.Column(column =>
        {
            column.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
            column.Item().PaddingTop(5);

            if (!string.IsNullOrEmpty(_branding.CustomFooter))
            {
                column.Item().AlignCenter().Text(_branding.CustomFooter)
                    .FontSize(8).FontColor(Colors.Grey.Medium);
            }
            else if (_branding.ShowProductAttribution)
            {
                column.Item().AlignCenter().Text(text =>
                {
                    text.Span("Generated by ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(_branding.ProductName).FontSize(8).FontColor(Colors.Grey.Medium).Bold();
                    text.Span($" for {_branding.CompanyName}").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span($" | {generatedAt:yyyy-MM-dd HH:mm}").FontSize(8).FontColor(Colors.Grey.Lighten1);
                });
            }
        });
    }

    private void ComposeContent(IContainer container, RolloutReport report)
    {
        container.Column(column =>
        {
            column.Item().Element(c => ComposeSummary(c, report));
            column.Item().PaddingTop(20).Element(c => ComposeDevices(c, report));

            if (report.Issues.Count > 0)
                column.Item().PaddingTop(20).Element(c => ComposeIssues(c, report));

            if (report.Notes.Count > 0)
                column.Item().PaddingTop(20).Element(c => ComposeNotes(c, report));
        });
    }

    private void ComposeSummary(IContainer container, RolloutReport report)
    {
        container.Column(column =>
        {
            SectionHeading(column, "Summary");

            column.Item().Row(row =>
            {
                row.RelativeItem().AlignMiddle().Column(headline =>
                {
                    headline.Item().AlignCenter().Text($"{report.TotalUpgraded}")
                        .FontSize(42).Bold().FontColor(_branding.Colors.Success);
                    headline.Item().AlignCenter().PaddingTop(2)
                        .Text(report.TotalUpgraded == 1 ? "Device upgraded" : "Devices upgraded")
                        .FontSize(9).FontColor(Colors.Grey.Medium);
                });

                row.RelativeItem(2).Column(detail =>
                {
                    LabelledLine(detail, "Started", TimeLabel(report.StartedAt));
                    LabelledLine(detail, "Finished", TimeLabel(report.CompletedAt));
                    LabelledLine(detail, "Took", FormatDuration(report.TotalSeconds));
                    LabelledLine(detail, "Failed", report.DevicesFailed.ToString());
                    LabelledLine(detail, "Rolled back", report.DevicesRolledBack.ToString());
                    LabelledLine(detail, "Skipped", report.DevicesSkipped.ToString());
                    LabelledLine(detail, "UniFi Network", ConsoleOutcomeWithVersions(report.UniFiNetworkUpdateOutcome, report.UniFiNetworkFromVersion, report.UniFiNetworkToVersion));
                    LabelledLine(detail, "UniFi OS", ConsoleOutcomeWithVersions(report.UniFiOsUpdateOutcome, report.UniFiOsFromVersion, report.UniFiOsToVersion));
                });
            });

            column.Item().PaddingTop(12).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2f);
                    columns.RelativeColumn(1f);
                    columns.RelativeColumn(1f);
                });

                HeaderRow(table, "Upgraded device resource use", "Before", "After");

                Cell(table, "CPU (mean)");
                Cell(table, FormatPercent(report.SiteCpuBeforeMean));
                Cell(table, FormatPercent(report.SiteCpuAfterMean));

                Cell(table, "Memory (mean)");
                Cell(table, FormatPercent(report.SiteMemBeforeMean));
                Cell(table, FormatPercent(report.SiteMemAfterMean));
            });
        });
    }

    private void ComposeDevices(IContainer container, RolloutReport report)
    {
        container.Column(column =>
        {
            SectionHeading(column, "Devices");

            if (report.Rows.Count == 0)
            {
                column.Item().Text("This rollout covered no devices.").FontSize(9).FontColor(Colors.Grey.Medium);
                return;
            }

            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2f);
                    columns.RelativeColumn(1.1f);
                    columns.RelativeColumn(1.6f);
                    columns.RelativeColumn(1.3f);
                    columns.RelativeColumn(0.9f);
                    columns.RelativeColumn(1.1f);
                    columns.RelativeColumn(1.1f);
                });

                HeaderRow(table, "Device", "Model", "Firmware", "Outcome", "Downtime", "CPU", "Memory");

                foreach (var row in report.Rows)
                {
                    Cell(table, row.Name);
                    Cell(table, row.Model);
                    // Short form, the same as every screen: the catalog names a build
                    // (7.5.10.17129) where the device reports a version (7.5.10).
                    Cell(table, $"{FirmwareVersionFormat.ShortOrNull(row.FromVersion) ?? "--"} to {FirmwareVersionFormat.ShortOrNull(row.ToVersion) ?? "--"}");
                    Cell(table, row.Outcome, OutcomeColor(row.Outcome));
                    Cell(table, row.DowntimeSeconds is int seconds ? FormatDuration(seconds) : "--");
                    Cell(table, BeforeAfter(row.CpuBeforeMean, row.CpuAfterMean));
                    Cell(table, BeforeAfter(row.MemBeforeMean, row.MemAfterMean));
                }
            });
        });
    }

    private void ComposeIssues(IContainer container, RolloutReport report)
    {
        container.Column(column =>
        {
            SectionHeading(column, "Issues");

            foreach (var issue in report.Issues)
            {
                column.Item().PaddingBottom(6).BorderLeft(2).BorderColor(_branding.Colors.Warning).PaddingLeft(8)
                    .Text(issue).FontSize(9);
            }
        });
    }

    private void ComposeNotes(IContainer container, RolloutReport report)
    {
        container.Column(column =>
        {
            SectionHeading(column, "How this rollout was planned");

            foreach (var note in report.Notes)
                column.Item().PaddingBottom(4).Text($"- {note}").FontSize(9).FontColor(Colors.Grey.Darken1);
        });
    }

    private static string WindowLabel(RolloutReport report)
    {
        if (report.StartedAt is not DateTime started)
            return "not started";
        return report.CompletedAt is DateTime completed
            ? $"{started.ToLocalTime():MMM d, yyyy HH:mm} - {completed.ToLocalTime():HH:mm}"
            : $"{started.ToLocalTime():MMM d, yyyy HH:mm}";
    }

    private static string TimeLabel(DateTime? time) =>
        time is DateTime value ? value.ToLocalTime().ToString("MMM d, yyyy HH:mm") : "--";

    private static string FormatDuration(int seconds)
    {
        if (seconds <= 0) return "--";
        var span = TimeSpan.FromSeconds(seconds);
        if (span.TotalHours >= 1) return $"{(int)span.TotalHours}h {span.Minutes}m";
        if (span.TotalMinutes >= 1) return $"{(int)span.TotalMinutes}m {span.Seconds}s";
        return $"{span.Seconds}s";
    }

    private static string FormatPercent(double? value) => value is double v ? $"{v:0.0}%" : "--";

    private static string BeforeAfter(double? before, double? after)
    {
        if (before == null && after == null) return "--";
        return $"{FormatPercent(before)} to {FormatPercent(after)}";
    }

    private static string ConsoleOutcomeLabel(string? outcome) => outcome switch
    {
        null or "" => "Not included",
        "updated" => "Updated",
        "nothing-to-update" => "Already current",
        "unchanged" => "Accepted but unchanged",
        "refused" => "Refused by the Console",
        "stuck" => "Did not come back",
        "skipped" => "Not included",
        _ => outcome,
    };

    private static string ConsoleOutcomeWithVersions(string? outcome, string? from, string? to)
    {
        var label = ConsoleOutcomeLabel(outcome);
        var fromShort = FirmwareVersionFormat.ShortOrNull(from);
        var toShort = FirmwareVersionFormat.ShortOrNull(to);
        if (outcome == "updated" && fromShort != null && toShort != null)
            return $"{fromShort} → {toShort}";
        if (outcome is "nothing-to-update" or "unchanged" && fromShort != null)
            return $"{label} {fromShort}";
        if (outcome == "stuck" && toShort != null)
            return $"{label}, targeting {toShort}";
        return label;
    }

    private string OutcomeColor(string outcome) => outcome switch
    {
        RolloutOutcomes.Upgraded => _branding.Colors.Success,
        RolloutOutcomes.RegressionFlagged or RolloutOutcomes.RolledBack => _branding.Colors.Warning,
        RolloutOutcomes.Failed => _branding.Colors.Critical,
        _ => Colors.Grey.Darken1,
    };

    private void SectionHeading(ColumnDescriptor column, string title) =>
        column.Item().PaddingBottom(10).Text(title)
            .FontSize(16).Bold().FontColor(_branding.Colors.Primary);

    private static void LabelledLine(ColumnDescriptor column, string label, string value) =>
        column.Item().PaddingBottom(2).Text(text =>
        {
            text.Span($"{label}: ").FontSize(9).FontColor(Colors.Grey.Medium);
            text.Span(value).FontSize(9);
        });

    private void HeaderRow(TableDescriptor table, params string[] headings)
    {
        var lightGray = _branding.Colors.LightGray;
        table.Header(header =>
        {
            foreach (var heading in headings)
                header.Cell().Background(lightGray).Padding(6).Text(heading).Bold().FontSize(9);
        });
    }

    private static void Cell(TableDescriptor table, string text, string? fontColor = null)
    {
        var cell = table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
            .Text(text).FontSize(9);
        if (fontColor != null) cell.FontColor(fontColor);
    }
}
