using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using NetworkOptimizer.Storage.Models;
using NetworkOptimizer.Storage.Models.Identity;
using NetworkOptimizer.Web.Services;
using NetworkOptimizer.Web.Services.Auditing;
using NetworkOptimizer.Web.Services.Identity;
using Xunit;

namespace NetworkOptimizer.Web.Tests.Identity;

/// <summary>
/// The Admin Password control in Settings stays where it always was, but it now writes the signed-in
/// user's Identity password, because that hash is what a sign-in checks. These tests run the same
/// sequence the control does against a real <see cref="UserManager{TUser}"/> and SQLite database: the
/// new password must authenticate afterwards, and the old one must not.
/// </summary>
public sealed class AdminPasswordChangeTests : IDisposable
{
    private readonly string _dbPath = Path.Combine(Path.GetTempPath(), $"netopt-pw-test-{Guid.NewGuid():N}.db");

    private ServiceProvider BuildProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDataProtection();

        var mainOptions = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        services.AddSingleton<IDbContextFactory<NetworkOptimizerDbContext>>(
            new NetworkOptimizerDbContextFactory(mainOptions));

        services.AddNetOptIdentityCore(_dbPath);
        services.AddSingleton<IAuditLogger>(new NoOpAuditLogger());
        services.AddScoped<ICallerContext, CallerContext>();
        services.AddScoped<NetworkOptimizer.Web.Services.Authorization.IEffectiveSiteRoleResolver, UnusedSiteRoleResolver>();
        // The admin credential store, as the Web host registers it.
        services.AddSingleton<IPasswordHasher, PasswordHasher>();
        services.AddSingleton<AdminAuthCache>();
        services.AddScoped<IAdminAuthService, AdminAuthService>();
        return services.BuildServiceProvider();
    }

    private async Task SeedAdminSettingsAsync(string password)
    {
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using var db = new NetworkOptimizerDbContext(options);
        await db.Database.MigrateAsync();
        db.AdminSettings.Add(new AdminSettings
        {
            Password = new PasswordHasher().HashPassword(password),
            Enabled = true,
        });
        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task PasswordChangedInSettings_AuthenticatesOnTheNextSignIn()
    {
        const string original = "Original-Pass-1";
        const string replacement = "Replacement-Pass-2";
        await SeedAdminSettingsAsync(original);

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId;
        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin.Should().NotBeNull();
            adminId = admin!.Id;
            (await userManager.CheckPasswordAsync(admin, original)).Should().BeTrue();
        }

        // What the Admin Password control does: set the signed-in user's own Identity password.
        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            var result = await identityAdmin.SetOwnPasswordAsync(adminId, replacement);
            result.Succeeded.Should().BeTrue(result.Error);
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            (await userManager.CheckPasswordAsync(admin!, replacement)).Should()
                .BeTrue("the password set in Settings is the one that signs in next time");
            (await userManager.CheckPasswordAsync(admin!, original)).Should()
                .BeFalse("the replaced password must stop working");
        }
    }

    [Fact]
    public async Task ChangingThePasswordClearsTheTemporaryFlag()
    {
        const string autoGenerated = "Auto-Gen-Pass-42";
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using (var db = new NetworkOptimizerDbContext(options))
        {
            await db.Database.MigrateAsync();
            // Enabled=false is the auto-generated first-run password, which stays flagged temporary.
            db.AdminSettings.Add(new AdminSettings
            {
                Password = new PasswordHasher().HashPassword(autoGenerated),
                Enabled = false,
            });
            await db.SaveChangesAsync();
        }

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId;
        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin!.PasswordIsTemporary.Should().BeTrue();
            adminId = admin.Id;
        }

        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.SetOwnPasswordAsync(adminId, "A-Real-Password-3")).Succeeded.Should().BeTrue();
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            admin!.PasswordIsTemporary.Should().BeFalse("the operator has now set a password of their own");
        }
    }

    [Fact]
    public async Task EnablingAuthenticationFromScratchSeedsAnAdminThatCanSignIn()
    {
        // A brand-new install with no AdminSettings row: no Identity account exists yet, so nobody
        // is signed in when the control is used. Saving a password and then running the bootstrap is
        // exactly the sequence the Admin Password control performs in that state.
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using (var db = new NetworkOptimizerDbContext(options))
            await db.Database.MigrateAsync();

        await using var provider = BuildProvider();
        using (var scope = provider.CreateScope())
        {
            var adminAuth = scope.ServiceProvider.GetRequiredService<IAdminAuthService>();
            await adminAuth.SaveAdminSettingsAsync("First-Admin-Pass-4", enabled: true);
            (await adminAuth.IsAuthenticationRequiredAsync()).Should().BeTrue();
        }

        using (var scope = provider.CreateScope())
            await scope.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin.Should().NotBeNull("turning authentication on must leave an account to sign in with");
            (await userManager.CheckPasswordAsync(admin!, "First-Admin-Pass-4")).Should().BeTrue();
            (await userManager.IsInRoleAsync(admin!, Roles.Admin)).Should().BeTrue();
        }
    }

    [Fact]
    public async Task SigningOutEverywhereRotatesTheStampAndLeavesTheCredentialAlone()
    {
        const string password = "Original-Pass-1";
        await SeedAdminSettingsAsync(password);

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId, stampBefore;
        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            adminId = admin!.Id;
            stampBefore = await userManager.GetSecurityStampAsync(admin);
        }

        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.SignOutEverywhereAsync(adminId)).Succeeded.Should().BeTrue();
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            (await userManager.GetSecurityStampAsync(admin!)).Should()
                .NotBe(stampBefore, "every live cookie is validated against the stamp, so rotating it is what ends the sessions");
            (await userManager.CheckPasswordAsync(admin!, password)).Should()
                .BeTrue("ending sessions must not lock the account out of signing back in");
        }
    }

    [Fact]
    public async Task DeletingTheAccountYouAreSignedInAsIsRefused()
    {
        await SeedAdminSettingsAsync("Original-Pass-1");

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string operatorId;
        using (var scope = provider.CreateScope())
        {
            // A second Admin, so the refusal cannot be the last-admin invariant firing instead.
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.CreateUserAsync("second", null, "Second-Pass-2", Roles.Admin))
                .Succeeded.Should().BeTrue();
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            operatorId = (await userManager.FindByNameAsync("second"))!.Id;
        }

        using (var scope = provider.CreateScope())
        {
            scope.ServiceProvider.GetRequiredService<ICallerContext>()
                .SetUser(CallerInfo.ForUser(PrincipalFor(operatorId), null, null, null));
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();

            var result = await identityAdmin.DeleteUserAsync(operatorId);
            result.Succeeded.Should().BeFalse("deleting your own account revokes your session mid-action");
            result.Error.Should().Contain("signed in as");
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            (await userManager.FindByIdAsync(operatorId)).Should().NotBeNull();
        }
    }

    [Fact]
    public async Task DeletingTheBuiltInAdminAccountIsRefusedButDisablingItIsNot()
    {
        await SeedAdminSettingsAsync("Original-Pass-1");

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId, otherId;
        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            // Another Admin exists, so neither refusal below can be the last-admin invariant.
            (await identityAdmin.CreateUserAsync("second", null, "Second-Pass-2", Roles.Admin))
                .Succeeded.Should().BeTrue();
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            adminId = (await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName))!.Id;
            otherId = (await userManager.FindByNameAsync("second"))!.Id;
        }

        using (var scope = provider.CreateScope())
        {
            scope.ServiceProvider.GetRequiredService<ICallerContext>()
                .SetUser(CallerInfo.ForUser(PrincipalFor(otherId), null, null, null));
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();

            var deleted = await identityAdmin.DeleteUserAsync(adminId);
            deleted.Succeeded.Should().BeFalse("the boot seed and break-glass recovery both rely on this account");
            deleted.Error.Should().Contain("Disable it instead");

            (await identityAdmin.SetEnabledAsync(adminId, false)).Succeeded.Should()
                .BeTrue("disabling the built-in account is the supported way to take it out of use");
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            admin.Should().NotBeNull();
            admin!.IsEnabled.Should().BeFalse();
        }
    }

    [Fact]
    public async Task DisablingOrDemotingYourOwnAccountIsRefused()
    {
        await SeedAdminSettingsAsync("Original-Pass-1");

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string selfId;
        using (var scope = provider.CreateScope())
        {
            // A second Admin exists, so neither refusal can be the last-admin invariant firing.
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.CreateUserAsync("second", null, "Second-Pass-2", Roles.Admin))
                .Succeeded.Should().BeTrue();
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            selfId = (await userManager.FindByNameAsync("second"))!.Id;
        }

        using (var scope = provider.CreateScope())
        {
            scope.ServiceProvider.GetRequiredService<ICallerContext>()
                .SetUser(CallerInfo.ForUser(PrincipalFor(selfId), null, null, null));
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();

            var disabled = await identityAdmin.SetEnabledAsync(selfId, false);
            disabled.Succeeded.Should().BeFalse("disabling yourself rotates your stamp and ends your session");
            disabled.Error.Should().Contain("signed in as");

            var demoted = await identityAdmin.RevokeGlobalRoleAsync(selfId, Roles.Admin);
            demoted.Succeeded.Should().BeFalse("dropping your own Admin role strips your access");
            demoted.Error.Should().Contain("your own Admin role");
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var self = await userManager.FindByIdAsync(selfId);
            self!.IsEnabled.Should().BeTrue();
            (await userManager.IsInRoleAsync(self, Roles.Admin)).Should().BeTrue();
        }
    }

    [Fact]
    public async Task AnotherAdminCanStillDisableAndDemoteYou()
    {
        await SeedAdminSettingsAsync("Original-Pass-1");

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId, targetId;
        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.CreateUserAsync("colleague", null, "Colleague-Pass-2", Roles.Admin))
                .Succeeded.Should().BeTrue();
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            adminId = (await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName))!.Id;
            targetId = (await userManager.FindByNameAsync("colleague"))!.Id;
        }

        using (var scope = provider.CreateScope())
        {
            // Signed in as the built-in admin, acting on somebody else: both changes are allowed.
            scope.ServiceProvider.GetRequiredService<ICallerContext>()
                .SetUser(CallerInfo.ForUser(PrincipalFor(adminId), null, null, null));
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();

            (await identityAdmin.RevokeGlobalRoleAsync(targetId, Roles.Admin)).Succeeded.Should().BeTrue();
            (await identityAdmin.SetEnabledAsync(targetId, false)).Succeeded.Should().BeTrue();
        }
    }

    private static System.Security.Claims.ClaimsPrincipal PrincipalFor(string userId)
        => new(new System.Security.Claims.ClaimsIdentity(
            new[]
            {
                new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.NameIdentifier, userId),
                new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.Role, Roles.Admin),
            },
            "test"));

    /// <summary>
    /// These tests act as a global Admin or with no caller at all, so the membership ownership guard
    /// never consults site roles. The resolver only has to exist for the container to build.
    /// </summary>
    private sealed class UnusedSiteRoleResolver : NetworkOptimizer.Web.Services.Authorization.IEffectiveSiteRoleResolver
    {
        public Task<SiteRole?> GetEffectiveRoleAsync(System.Security.Claims.ClaimsPrincipal user, string slug)
            => Task.FromResult<SiteRole?>(null);

        public Task<IReadOnlySet<string>> GetAuthorizedSlugsAsync(System.Security.Claims.ClaimsPrincipal user)
            => Task.FromResult<IReadOnlySet<string>>(new HashSet<string>());
    }

    private sealed class NoOpAuditLogger : IAuditLogger
    {
        public void Log(AuditEvent auditEvent) { }
    }

    public void Dispose()
    {
        try
        {
            if (File.Exists(_dbPath)) File.Delete(_dbPath);
        }
        catch (IOException) { /* temp file, ignored */ }
    }
}
