using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using NetworkOptimizer.Storage.Models;
using NetworkOptimizer.Storage.Models.Identity;
using NetworkOptimizer.Web.Services;
using NetworkOptimizer.Web.Services.Auditing;
using NetworkOptimizer.Web.Services.Identity;
using Xunit;

namespace NetworkOptimizer.Web.Tests.Identity;

/// <summary>
/// The Admin Password control in Settings stays where it always was, but it now writes the signed-in
/// user's Identity password, because that hash is what a sign-in checks. These tests run the same
/// sequence the control does against a real <see cref="UserManager{TUser}"/> and SQLite database: the
/// new password must authenticate afterwards, and the old one must not.
/// </summary>
public sealed class AdminPasswordChangeTests : IDisposable
{
    private readonly string _dbPath = Path.Combine(Path.GetTempPath(), $"netopt-pw-test-{Guid.NewGuid():N}.db");

    private ServiceProvider BuildProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDataProtection();

        var mainOptions = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        services.AddSingleton<IDbContextFactory<NetworkOptimizerDbContext>>(
            new NetworkOptimizerDbContextFactory(mainOptions));

        services.AddNetOptIdentityCore(_dbPath);
        services.AddSingleton<IAuditLogger>(new NoOpAuditLogger());
        services.AddScoped<ICallerContext, CallerContext>();
        // The admin credential store, as the Web host registers it.
        services.AddSingleton<IPasswordHasher, PasswordHasher>();
        services.AddSingleton<AdminAuthCache>();
        services.AddScoped<IAdminAuthService, AdminAuthService>();
        return services.BuildServiceProvider();
    }

    private async Task SeedAdminSettingsAsync(string password)
    {
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using var db = new NetworkOptimizerDbContext(options);
        await db.Database.MigrateAsync();
        db.AdminSettings.Add(new AdminSettings
        {
            Password = new PasswordHasher().HashPassword(password),
            Enabled = true,
        });
        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task PasswordChangedInSettings_AuthenticatesOnTheNextSignIn()
    {
        const string original = "Original-Pass-1";
        const string replacement = "Replacement-Pass-2";
        await SeedAdminSettingsAsync(original);

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId;
        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin.Should().NotBeNull();
            adminId = admin!.Id;
            (await userManager.CheckPasswordAsync(admin, original)).Should().BeTrue();
        }

        // What the Admin Password control does: set the signed-in user's own Identity password.
        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            var result = await identityAdmin.SetOwnPasswordAsync(adminId, replacement);
            result.Succeeded.Should().BeTrue(result.Error);
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            (await userManager.CheckPasswordAsync(admin!, replacement)).Should()
                .BeTrue("the password set in Settings is the one that signs in next time");
            (await userManager.CheckPasswordAsync(admin!, original)).Should()
                .BeFalse("the replaced password must stop working");
        }
    }

    [Fact]
    public async Task ChangingThePasswordClearsTheTemporaryFlag()
    {
        const string autoGenerated = "Auto-Gen-Pass-42";
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using (var db = new NetworkOptimizerDbContext(options))
        {
            await db.Database.MigrateAsync();
            // Enabled=false is the auto-generated first-run password, which stays flagged temporary.
            db.AdminSettings.Add(new AdminSettings
            {
                Password = new PasswordHasher().HashPassword(autoGenerated),
                Enabled = false,
            });
            await db.SaveChangesAsync();
        }

        await using var provider = BuildProvider();
        using (var boot = provider.CreateScope())
            await boot.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        string adminId;
        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin!.PasswordIsTemporary.Should().BeTrue();
            adminId = admin.Id;
        }

        using (var scope = provider.CreateScope())
        {
            var identityAdmin = scope.ServiceProvider.GetRequiredService<IIdentityAdminService>();
            (await identityAdmin.SetOwnPasswordAsync(adminId, "A-Real-Password-3")).Succeeded.Should().BeTrue();
        }

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByIdAsync(adminId);
            admin!.PasswordIsTemporary.Should().BeFalse("the operator has now set a password of their own");
        }
    }

    [Fact]
    public async Task EnablingAuthenticationFromScratchSeedsAnAdminThatCanSignIn()
    {
        // A brand-new install with no AdminSettings row: no Identity account exists yet, so nobody
        // is signed in when the control is used. Saving a password and then running the bootstrap is
        // exactly the sequence the Admin Password control performs in that state.
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using (var db = new NetworkOptimizerDbContext(options))
            await db.Database.MigrateAsync();

        await using var provider = BuildProvider();
        using (var scope = provider.CreateScope())
        {
            var adminAuth = scope.ServiceProvider.GetRequiredService<IAdminAuthService>();
            await adminAuth.SaveAdminSettingsAsync("First-Admin-Pass-4", enabled: true);
            (await adminAuth.IsAuthenticationRequiredAsync()).Should().BeTrue();
        }

        using (var scope = provider.CreateScope())
            await scope.ServiceProvider.GetRequiredService<IIdentityBootstrapService>().RunAsync();

        using (var scope = provider.CreateScope())
        {
            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            admin.Should().NotBeNull("turning authentication on must leave an account to sign in with");
            (await userManager.CheckPasswordAsync(admin!, "First-Admin-Pass-4")).Should().BeTrue();
            (await userManager.IsInRoleAsync(admin!, GlobalRoles.Admin)).Should().BeTrue();
        }
    }

    private sealed class NoOpAuditLogger : IAuditLogger
    {
        public void Log(AuditEvent auditEvent) { }
    }

    public void Dispose()
    {
        try
        {
            if (File.Exists(_dbPath)) File.Delete(_dbPath);
        }
        catch (IOException) { /* temp file, ignored */ }
    }
}
