using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using NetworkOptimizer.Storage.Models;
using NetworkOptimizer.Storage.Models.Identity;
using NetworkOptimizer.Web.Services;
using NetworkOptimizer.Web.Services.Auditing;
using NetworkOptimizer.Web.Services.Identity;
using Xunit;

namespace NetworkOptimizer.Web.Tests.Identity;

/// <summary>
/// End-to-end proof that the identity bootstrap seeds a working <c>admin</c> account from the
/// install's existing local credential, driven through a real <see cref="UserManager{TUser}"/> and a
/// real SQLite database (migrations applied). The auto-generated-password path is the highest-risk
/// case: if the transcode-then-seed is wrong, the lazy-homelabber install can't log in after the
/// JWT-to-cookie cutover (design doc 02).
/// </summary>
public sealed class IdentityBootstrapServiceTests : IDisposable
{
    private readonly string _dbPath = Path.Combine(Path.GetTempPath(), $"netopt-auth-test-{Guid.NewGuid():N}.db");

    private ServiceProvider BuildProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        // The Web host registers Data Protection; the default Identity token providers depend on it.
        services.AddDataProtection();

        var mainOptions = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        services.AddSingleton<IDbContextFactory<NetworkOptimizerDbContext>>(
            new NetworkOptimizerDbContextFactory(mainOptions));

        services.AddNetOptIdentityCore(_dbPath);
        // Override the channel-based audit logger (whose writer pulls in forwarding/settings deps
        // not present in this minimal container) with a no-op; the seed path doesn't assert on audit.
        services.AddSingleton<IAuditLogger>(new NoOpAuditLogger());
        return services.BuildServiceProvider();
    }

    private async Task SeedLegacyAdminSettingsAsync(string legacyHash, bool enabled)
    {
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using var db = new NetworkOptimizerDbContext(options);
        await db.Database.MigrateAsync();
        db.AdminSettings.Add(new AdminSettings { Password = legacyHash, Enabled = enabled });
        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task AutoGeneratedPassword_SeedsAdmin_LoginWorks_AndStaysTemporary()
    {
        // Arrange: an auto-generated first-run password (Enabled=false), stored as a legacy hash.
        const string tempPassword = "Auto-Gen-Pass-42";
        var legacyHash = new PasswordHasher().HashPassword(tempPassword);
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: false);

        await using var provider = BuildProvider();

        // Act
        await RunBootstrapAsync(provider);

        // Assert: admin exists, in the Admin role, temp-flagged, and the temp password authenticates.
        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin.Should().NotBeNull();
        admin!.PasswordIsTemporary.Should().BeTrue("an auto-generated password must keep nagging");
        admin.IsEnabled.Should().BeTrue();
        (await userManager.IsInRoleAsync(admin, Roles.Admin)).Should().BeTrue();
        (await userManager.CheckPasswordAsync(admin, tempPassword)).Should()
            .BeTrue("the migrated temp password must still log in - this is the anti-lockout guarantee");
        (await userManager.CheckPasswordAsync(admin, "wrong")).Should().BeFalse();
    }

    [Fact]
    public async Task EnabledDbPassword_SeedsNonTemporaryAdmin()
    {
        const string dbPassword = "User-Chosen-Pw-7";
        var legacyHash = new PasswordHasher().HashPassword(dbPassword);
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin!.PasswordIsTemporary.Should().BeFalse("a user-enabled DB password is not temporary");
        (await userManager.CheckPasswordAsync(admin, dbPassword)).Should().BeTrue();
    }

    [Fact]
    public async Task Bootstrap_IsIdempotent_NoDuplicateAdminOnRerun()
    {
        var legacyHash = new PasswordHasher().HashPassword("Some-Pass-9");
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        userManager.Users.Count(u => u.UserName == IdentityBootstrapService.AdminUserName).Should().Be(1);
    }

    [Fact]
    public async Task NoLocalCredential_SkipsSeed()
    {
        // Main DB exists (migrated) but no AdminSettings row and no APP_PASSWORD.
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}").Options;
        await using (var db = new NetworkOptimizerDbContext(options))
            await db.Database.MigrateAsync();

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        // Roles are still ensured, but no admin user is seeded without a credential.
        (await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName)).Should().BeNull();
        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<ApplicationRole>>();
        (await roleManager.RoleExistsAsync(Roles.Admin)).Should().BeTrue();
    }

    /// <summary>
    /// The first run on a brand-new install: nothing stored, so the password is generated and the
    /// admin account is created straight from the plaintext. This one goes through Identity's
    /// password validators, so a generated password that broke the policy would leave the install
    /// with no admin account at all - the worst outcome available on this path.
    /// </summary>
    [Fact]
    public async Task FirstRun_WithNoStoredCredential_CreatesAWorkingAdminFromTheGeneratedPassword()
    {
        // No AdminSettings row at all, exactly like a fresh install.
        await using var provider = BuildProvider();

        const string generated = "Generated-First-Run-7";
        provider.GetRequiredService<AdminAuthCache>().PublishFirstRunPassword(generated);
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin.Should().NotBeNull("a failed create would leave a fresh install with no way in");
        (await users.CheckPasswordAsync(admin!, generated)).Should().BeTrue();
        (await users.IsInRoleAsync(admin!, Roles.Admin)).Should().BeTrue();
        admin!.PasswordIsTemporary.Should().BeTrue();
        admin.IsEnabled.Should().BeTrue();
    }

    /// <summary>
    /// An upgrading install brings whatever password it already had, which predates the account
    /// policy and need not satisfy it. The seed copies the transcoded hash and calls the overload
    /// that runs only the user validators, so the policy is never evaluated and nobody is locked
    /// out by the cutover. If this ever starts validating, short legacy passwords stop migrating.
    /// </summary>
    [Fact]
    public async Task LegacyPasswordThatBreaksThePolicy_StillMigratesAndSignsIn()
    {
        // Too short and no digit: rejected outright if it were ever put through the validators.
        const string weakPassword = "abc";
        await SeedLegacyAdminSettingsAsync(new PasswordHasher().HashPassword(weakPassword), enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin.Should().NotBeNull("an upgrade must never lock the operator out over password strength");
        (await users.CheckPasswordAsync(admin!, weakPassword)).Should().BeTrue();
        (await users.IsInRoleAsync(admin!, Roles.Admin)).Should().BeTrue();
    }

    /// <summary>
    /// The reset scripts clear the stored password so startup regenerates one and prints it. Once an
    /// admin account exists, only re-applying that password to the account makes the printed one the
    /// real login - without it the scripts hand out a password that is silently refused.
    /// </summary>
    [Fact]
    public async Task RegeneratedFirstRunPassword_ResetsAnAlreadySeededAdmin()
    {
        const string oldPassword = "Original-Pass-42";
        await SeedLegacyAdminSettingsAsync(new PasswordHasher().HashPassword(oldPassword), enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        // The operator has been failing sign-ins, so the account is locked out too.
        using (var scope = provider.CreateScope())
        {
            var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var locked = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            locked!.LockoutEnd = DateTimeOffset.UtcNow.AddMinutes(5);
            locked.AccessFailedCount = 5;
            await users.UpdateAsync(locked);
        }

        // Act: reset-password.* cleared the row, so AdminAuthService generated and printed this one.
        const string resetPassword = "Regenerated-Pass-99";
        provider.GetRequiredService<AdminAuthCache>().PublishFirstRunPassword(resetPassword);
        await RunBootstrapAsync(provider);

        using (var scope = provider.CreateScope())
        {
            var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);

            (await users.CheckPasswordAsync(admin!, resetPassword)).Should().BeTrue(
                "the password the reset printed is the one that must now work");
            (await users.CheckPasswordAsync(admin!, oldPassword)).Should().BeFalse(
                "the password that was reset away must stop working");
            admin!.PasswordIsTemporary.Should().BeTrue("a generated password still needs replacing");
            admin.LockoutEnd.Should().BeNull("a reset is worthless if the account stays locked out");
            admin.AccessFailedCount.Should().Be(0);
        }
    }

    /// <summary>
    /// A stored hash that was only read back must not re-apply on later boots, or every restart
    /// would overwrite whatever password the user has since set through Identity.
    /// </summary>
    [Fact]
    public async Task StoredLegacyHash_DoesNotOverwriteALaterPasswordOnReboot()
    {
        await SeedLegacyAdminSettingsAsync(new PasswordHasher().HashPassword("Seeded-Pass-42"), enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        const string chosenPassword = "Chosen-In-App-77";
        using (var scope = provider.CreateScope())
        {
            var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            var token = await users.GeneratePasswordResetTokenAsync(admin!);
            (await users.ResetPasswordAsync(admin!, token, chosenPassword)).Succeeded.Should().BeTrue();
        }

        await RunBootstrapAsync(provider); // reboot, legacy row untouched

        using (var scope = provider.CreateScope())
        {
            var users = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var admin = await users.FindByNameAsync(IdentityBootstrapService.AdminUserName);
            (await users.CheckPasswordAsync(admin!, chosenPassword)).Should().BeTrue();
        }
    }

    /// <summary>
    /// The generated password is applied through Identity now, which enforces the account policy -
    /// so it has to satisfy RequireDigit. Drawing uniformly from the alphabet leaves roughly one in
    /// twelve with no digit at all, which would fail the reset it is meant to perform.
    /// </summary>
    [Fact]
    public void GeneratedFirstRunPassword_AlwaysSatisfiesThePasswordPolicy()
    {
        var generate = typeof(AdminAuthService).GetMethod(
            "GenerateSecurePassword",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
        generate.Should().NotBeNull("the first-run password generator is expected on AdminAuthService");

        for (var i = 0; i < 500; i++)
        {
            var password = (string)generate!.Invoke(null, null)!;
            password.Length.Should().BeGreaterThanOrEqualTo(8);
            password.Any(char.IsDigit).Should().BeTrue("Identity's RequireDigit rejects the rest");
        }
    }

    private static async Task RunBootstrapAsync(ServiceProvider provider)
    {
        using var scope = provider.CreateScope();
        var bootstrap = scope.ServiceProvider.GetRequiredService<IIdentityBootstrapService>();
        await bootstrap.RunAsync();
    }

    private sealed class NoOpAuditLogger : IAuditLogger
    {
        public void Log(AuditEvent auditEvent) { }
    }

    public void Dispose()
    {
        // SQLite may hold the file briefly; best-effort cleanup.
        try
        {
            if (File.Exists(_dbPath)) File.Delete(_dbPath);
        }
        catch (IOException) { /* temp file, ignored */ }
    }
}
