using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using NetworkOptimizer.Storage.Models;
using NetworkOptimizer.Storage.Models.Identity;
using NetworkOptimizer.Web.Services;
using NetworkOptimizer.Web.Services.Auditing;
using NetworkOptimizer.Web.Services.Identity;
using Xunit;

namespace NetworkOptimizer.Web.Tests.Identity;

/// <summary>
/// End-to-end proof that the identity bootstrap seeds a working <c>admin</c> account from the
/// install's existing local credential, driven through a real <see cref="UserManager{TUser}"/> and a
/// real SQLite database (migrations applied). The auto-generated-password path is the highest-risk
/// case: if the transcode-then-seed is wrong, the lazy-homelabber install can't log in after the
/// JWT-to-cookie cutover (design doc 02).
/// </summary>
public sealed class IdentityBootstrapServiceTests : IDisposable
{
    private readonly string _dbPath = Path.Combine(Path.GetTempPath(), $"netopt-auth-test-{Guid.NewGuid():N}.db");

    private ServiceProvider BuildProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        // The Web host registers Data Protection; the default Identity token providers depend on it.
        services.AddDataProtection();

        var mainOptions = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        services.AddSingleton<IDbContextFactory<NetworkOptimizerDbContext>>(
            new NetworkOptimizerDbContextFactory(mainOptions));

        services.AddNetOptIdentityCore(_dbPath);
        // Override the channel-based audit logger (whose writer pulls in forwarding/settings deps
        // not present in this minimal container) with a no-op; the seed path doesn't assert on audit.
        services.AddSingleton<IAuditLogger>(new NoOpAuditLogger());
        return services.BuildServiceProvider();
    }

    private async Task SeedLegacyAdminSettingsAsync(string legacyHash, bool enabled)
    {
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}")
            .Options;
        await using var db = new NetworkOptimizerDbContext(options);
        await db.Database.MigrateAsync();
        db.AdminSettings.Add(new AdminSettings { Password = legacyHash, Enabled = enabled });
        await db.SaveChangesAsync();
    }

    [Fact]
    public async Task AutoGeneratedPassword_SeedsAdmin_LoginWorks_AndStaysTemporary()
    {
        // Arrange: an auto-generated first-run password (Enabled=false), stored as a legacy hash.
        const string tempPassword = "Auto-Gen-Pass-42";
        var legacyHash = new PasswordHasher().HashPassword(tempPassword);
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: false);

        await using var provider = BuildProvider();

        // Act
        await RunBootstrapAsync(provider);

        // Assert: admin exists, in the Admin role, temp-flagged, and the temp password authenticates.
        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin.Should().NotBeNull();
        admin!.PasswordIsTemporary.Should().BeTrue("an auto-generated password must keep nagging");
        admin.IsEnabled.Should().BeTrue();
        (await userManager.IsInRoleAsync(admin, Roles.Admin)).Should().BeTrue();
        (await userManager.CheckPasswordAsync(admin, tempPassword)).Should()
            .BeTrue("the migrated temp password must still log in - this is the anti-lockout guarantee");
        (await userManager.CheckPasswordAsync(admin, "wrong")).Should().BeFalse();
    }

    [Fact]
    public async Task EnabledDbPassword_SeedsNonTemporaryAdmin()
    {
        const string dbPassword = "User-Chosen-Pw-7";
        var legacyHash = new PasswordHasher().HashPassword(dbPassword);
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var admin = await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName);

        admin!.PasswordIsTemporary.Should().BeFalse("a user-enabled DB password is not temporary");
        (await userManager.CheckPasswordAsync(admin, dbPassword)).Should().BeTrue();
    }

    [Fact]
    public async Task Bootstrap_IsIdempotent_NoDuplicateAdminOnRerun()
    {
        var legacyHash = new PasswordHasher().HashPassword("Some-Pass-9");
        await SeedLegacyAdminSettingsAsync(legacyHash, enabled: true);

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        userManager.Users.Count(u => u.UserName == IdentityBootstrapService.AdminUserName).Should().Be(1);
    }

    [Fact]
    public async Task NoLocalCredential_SkipsSeed()
    {
        // Main DB exists (migrated) but no AdminSettings row and no APP_PASSWORD.
        var options = new DbContextOptionsBuilder<NetworkOptimizerDbContext>()
            .UseSqlite($"Data Source={_dbPath}").Options;
        await using (var db = new NetworkOptimizerDbContext(options))
            await db.Database.MigrateAsync();

        await using var provider = BuildProvider();
        await RunBootstrapAsync(provider);

        using var scope = provider.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        // Roles are still ensured, but no admin user is seeded without a credential.
        (await userManager.FindByNameAsync(IdentityBootstrapService.AdminUserName)).Should().BeNull();
        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<ApplicationRole>>();
        (await roleManager.RoleExistsAsync(Roles.Admin)).Should().BeTrue();
    }

    private static async Task RunBootstrapAsync(ServiceProvider provider)
    {
        using var scope = provider.CreateScope();
        var bootstrap = scope.ServiceProvider.GetRequiredService<IIdentityBootstrapService>();
        await bootstrap.RunAsync();
    }

    private sealed class NoOpAuditLogger : IAuditLogger
    {
        public void Log(AuditEvent auditEvent) { }
    }

    public void Dispose()
    {
        // SQLite may hold the file briefly; best-effort cleanup.
        try
        {
            if (File.Exists(_dbPath)) File.Delete(_dbPath);
        }
        catch (IOException) { /* temp file, ignored */ }
    }
}
